### ISSUE TITLE
Path handling prepends working directory

### ISSUE THREAD

**Issue by josch1710** [psmedley/qt-creator-os2#1]
If one opens a file, the file handling code treats our drive oriented, DOS style path names as relative paths.
So, QtCreator prepends its working directory path to the selected path.
To test it, open a file.

**Comment by psmedley** [comment]
Can you try https://smedley.id.au/tmp/propars8.zip and see if it helps?
There are issues with starting processes which I almost assumed would be the case based on the hackery I did to get https://github.com/psmedley/qt6-base-os2/blob/main/src/corelib/io/qprocess_os2.cpp building

**Comment by psmedley** [comment]
Also, please install https://smedley.id.au/tmp/qt6core-20221204.zip

**Comment by josch1710** [comment]
When I construct a Qt Kit, I can select compiler binaries and such things and the correct path is applied.
But I still can't open a project file.

**Comment by psmedley** [comment]
Yep, I see this too

**Comment by psmedley** [comment]
I think this is the issue: https://github.com/psmedley/qt-creator-os2/blob/main/src/libs/utils/filepath.cpp#L360

**Comment by psmedley** [comment]
Possible fix for this in https://github.com/psmedley/qt-creator-os2/commit/943a3f9a4d4057f2ef448eb8e8959730d6a3f866

Test utils8.dll at https://smedley.id.au/tmp/utils8.zip seems to fix this.

**Comment by josch1710** [comment]
Yes, now I can open files and projects.
