### ISSUE TITLE
Binaries can't be started.

### ISSUE THREAD

**Issue by josch1710** [psmedley/qt-creator-os2#2]
To work with QtCreator Kits, one has select some binaries, like qmake6.exe or gcc.exe.
After selection QtCreator complains about not being able to execute the selected binaries.

**Comment by psmedley** [comment]
Pretty sure this is https://github.com/psmedley/qt6-base-os2/issues/4

**Comment by psmedley** [comment]
Fixed in https://github.com/psmedley/qt-creator-os2/commit/c6be1139e3ccbc93319a897754be47ce2ef1aeff
